# Generated by Django 4.2.20 on 2025-04-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_alter_cookuser_options_follow_follow_unique_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="foodgram/frontend/src/images/userpic-icon.jpg",
                null=True,
                upload_to="avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
