# Generated by Django 4.2.20 on 2025-04-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_alter_cookuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookuser",
            name="avatar",
            field=models.ImageField(
                default="foodgram/frontend/src/images/userpic-icon.jpg",
                null=True,
                upload_to="avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
