# Generated by Django 4.2.20 on 2025-04-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_alter_cookuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
    ]
