# Generated by Django 4.2.20 on 2025-04-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_alter_cookuser_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="unit",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(
                default=1, max_length=30, verbose_name="Единица измерения"
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("name", "measurement_unit"), name="unique_ingredient_unit"
            ),
        ),
    ]
