# Generated by Django 4.2.20 on 2025-04-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0006_rename_title_ingredient_name_rename_title_tag_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="cook_time",
            new_name="cooking_time",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="title",
            new_name="name",
        ),
    ]
