# Generated by Django 4.2.20 on 2025-04-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0007_rename_cook_time_recipe_cooking_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
    ]
