# Generated by Django 4.2.20 on 2025-04-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0009_recipeingredient_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(related_name="recipes", to="food.tag"),
        ),
    ]
