# Generated by Django 4.2.20 on 2025-04-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0011_alter_recipeingredient_options_recipe_short_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="short_link",
        ),
    ]
