# Generated by Django 4.2.20 on 2025-04-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0014_alter_recipe_short_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="short_link",
        ),
    ]
