# Generated by Django 4.2.20 on 2025-04-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0015_remove_recipe_short_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="short_link",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                unique=True,
                verbose_name="Хеш для короткой ссылки",
            ),
        ),
    ]
